job_ads_group_project:
  outputs:
    dev:
      type: duckdb
      path: C:\Users\pepef\Desktop\gp\AI_2_group_project/job_ads_data_warehouse.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
