sources:
  - name: job_ads
    description: "job_ads raw data source"
    schema: staging
    tables:

      - name: stg_ads
        description: "Main-table used for creating models"
        identifier: job_ads
        meta:
          dagster:
            asset_key: ['dlt_jobads_source_get_hits']

      - name: stg_driving_license
        description: "Table containing drivers license type"
        identifier: job_ads__driving_license

      - name: stg_must_skills
        description: "Table containing skills needed for job ad"
        identifier: job_ads__must_have__skills